### ISSUE TITLE
Question about the bPQ metric.

### ISSUE THREAD

**Issue by windygoo** [TIO-IKIM/CellViT#25]
From your provided logs in 'logs_paper/PanNuke/CellViTHV/SAM-H', the bPQ for three folds is 0.6633524845383327, 0.6624584712676017 and 0.6711352126330197, respectively. And thus, the average value is 0.6656487228129847, which I find is different from 0.6793 reported in your paper. How to explain it?

**Comment by FabianHoerst** [comment]
Could you be more specific? Which bPQ do you mean? Please refer to the respective table.

**Comment by fengkh** [comment]
same question on the mPQ calculation, Please @FabianHoerst

**Comment by FabianHoerst** [comment]
Hello, sorry for coming back so late. As this repo is not actively maintained anymore and due to limited capacity, I rarely check the issues. The same logic for the bPQ also applies to mPQ, but before averaging, classify the nuclei into each type and then perform the above mentioned steps. For more information, you can check out https://github.com/TissueImageAnalytics/PanNuke-metrics. However, mPQ can be sometimes "missleading", If you want further info, check out this paper and the code there https://www.sciencedirect.com/science/article/pii/S1361841522003139?via%3Dihub. I will close the other issue now 😊
